# Generated by Django 4.0.4 on 2022-05-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(db_index=True, max_length=150, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL категории')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок пара слов о категории (Необязательно)')),
            ],
            options={
                'verbose_name': 'Добавить категории к статьям',
                'verbose_name_plural': 'Добавить категории к статьям',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('header2', models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('image_preview', models.ImageField(upload_to='photo_preview/%Y/%m/%d/', verbose_name='Главное фото')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Поста')),
                ('category_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category_post', verbose_name='Категория статьи')),
            ],
            options={
                'verbose_name': 'Глерея работ/статья',
                'verbose_name_plural': 'Галерея работ/статьи',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото статьи')),
                ('description_photo', models.CharField(blank=True, max_length=250, verbose_name='Описание фото (необязательно)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Статья в которую фото')),
            ],
            options={
                'verbose_name': 'Добавить фото',
                'verbose_name_plural': 'Добавить фотографии к статьям',
            },
        ),
    ]
